CourseProjectDB/Areas/Admin/Controllers/CurrencyController.cs
using CourseProjectDB.Areas.Customer.Controllers;
using CP.DataAccess.Data;
using CP.DataAccess.Repository;
using CP.DataAccess.Repository.IRepository;
using CP.Models;
using CP.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace CourseProjectDB.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize(Roles = "Admin, Employee")]
	public class CurrencyController : Controller
	{
		private readonly IRegister _register;

		public CurrencyController(IRegister register)
		{
			_register = register;
		}

		public IActionResult Index()
		{
			List<InfoAboutCurrency> objectsFromDb = _register.CurrencyInfo.GetAll().ToList();
			return View(objectsFromDb);
		}
		public IActionResult Upsert(int? id) // update + insert = upsert))
		{ 
			InfoAboutCurrency IAC = new();
			if(id == null || id == 0)
			{
				return View(IAC);
			}
			else
			{
				IAC = _register.CurrencyInfo.GetFirstOrDefault(u=> u.ID == id);
				return View(IAC);
			}
		}
		[HttpPost]
		public IActionResult Upsert(InfoAboutCurrency IAC) 
		{
			if(IAC.ID == 0) 
			{
				List <InfoAboutCurrency> CurrListFromDb = _register.CurrencyInfo
					.GetAll(u => u.Name == IAC.Name).ToList();

				if (!CurrListFromDb.IsNullOrEmpty()) 
				{
					ModelState.AddModelError("name","Валюта із таким кодом уже існує");
					return View(IAC);
                }
				_register.CurrencyInfo.Add(IAC);
				TempData["success"] = "Валюту було додано успішно!";
			}
			else
			{
				_register.CurrencyInfo.Update(IAC);
				TempData["success"] = "Валюту було оновлено успішно!";
			}
			_register.Save();
			return RedirectToAction("Index");
		}

		#region API CALLS
		[HttpGet]
		public IActionResult GetAll()
		{
			List<InfoAboutCurrency> ObjectsFromDb = _register.CurrencyInfo.GetAll().ToList();
			return Json(new { data = ObjectsFromDb });
		}
		[HttpDelete]
		public IActionResult Delete(int? id) 
		{ 
			var CurrencyToBeDeleted = _register.CurrencyInfo.GetFirstOrDefault(u=>u.ID== id);
			if (CurrencyToBeDeleted == null)
			{
				return Json(new { succes = false, message = "Помилка під час видалення" });
			}
			List<Purchase> purchases = _register.Purchase.GetAll().ToList();
			foreach (Purchase purchase in purchases)
			{
				if (purchase.CurrencyID == id)
				{
					purchase.CurrencyID = null;
				}
			}
			_register.CurrencyInfo.Delete(CurrencyToBeDeleted);
			_register.Save();

			return Json(new { succes = true, message = "Валюту було видалено успішно!" });
		}
		#endregion
	}
}

CourseProjectDB/Areas/Admin/Controllers/PaymentsController.cs
using CP.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using CP.Models;
using CP.Models.VModels;
using CP.Utility.StatciData;

namespace CourseProjectDB.Areas.Admin.Controllers
{
    [Authorize]
	[Area("Admin")]
	[Authorize(Roles = SD.Role_Admin)]
	public class PaymentsController : Controller
	{
		private readonly IRegister _register;

		public PaymentsController(IRegister register)
		{
			_register = register;
		}

		public IActionResult Index()
		{
			List<Payments> objectsFromDb = _register.Payments.GetAll().ToList();
			return View(objectsFromDb);
		}
		public IActionResult Check(int id) 
		{
			var Payment = _register.Payments.GetFirstOrDefault(u => u.ID == id);
			return View(Payment);
		}
		public IActionResult Insert() 
		{
			Dictionary<string, string> list = new Dictionary<string, string>()
			{
				{ SD.Payments_Type_BC , SD.Payments_Type_BC },
				{ SD.Payments_Type_Util, SD.Payments_Type_Util },
				{ SD.Payments_Type_Salary, SD.Payments_Type_Salary}
			};
			PaymentsVM paymentsVM = new()
			{
				CurrencyList = _register.CurrencyInfo.GetAll()
				.Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.ID.ToString()
				}),
				EmployeeList = _register.User.GetAll(u => u.role == SD.Role_Employee)
				.Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.ID.ToString()
				}),
				PaymentsTypeList = list.Select(u => new SelectListItem
				{
					Text = u.Value,
					Value = u.Key.ToString()
				}),
				Payments = new Payments()
			};
			return View(paymentsVM);
		}
		[HttpPost]
		public IActionResult Insert(PaymentsVM paymentsVM, int? selectedEmployeeId, int? selectedCurrencyId)
		{
			paymentsVM.Payments.DateOfMakingPayments = DateTime.Now;
			if (paymentsVM.Payments.ID == 0)
			{
				if(paymentsVM.Payments.Type == SD.Payments_Type_Salary) 
				{
					var selectedEmployee = _register.User.GetFirstOrDefault(u=> u.ID == selectedEmployeeId);
					paymentsVM.Payments.Description += "\n\n  Заробітня плата для працівника "
						+ selectedEmployee.Name +" була виплачена у розмірі "+ paymentsVM.Payments.Sum+" UAH.";
						
				}
				if(paymentsVM.Payments.Type == SD.Payments_Type_BC) 
				{
					var selectedCurrency = _register.CurrencyInfo.GetFirstOrDefault(u => u.ID == selectedCurrencyId);

					int CurrencyAdd = (int)(paymentsVM.Payments.Sum / selectedCurrency.AskedCoursePriceTo);
					selectedCurrency.AvailOfAskedCourse += CurrencyAdd;
					_register.CurrencyInfo.Update(selectedCurrency);

					paymentsVM.Payments.Description += "\n\n  Було закуплено валюту "
						+ selectedCurrency.Name + " на суму " + paymentsVM.Payments.Sum + " UAH.";
				}
				_register.Payments.Add(paymentsVM.Payments);
				TempData["success"] = "Платіж було створено успішно!";
			}
			_register.Save();
			return RedirectToAction("Index");
		}
	}
}

CourseProjectDB/Areas/Admin/Controllers/RequestsController.cs
using CP.DataAccess.Repository.IRepository;
using CP.Models;
using CP.Models.VModels;
using CP.Utility.StatciData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using System.Collections;
using System.Collections.Generic;
using System.Security.Claims;

namespace CourseProjectDB.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class RequestsController : Controller
    {
        private readonly IRegister _register;
        public RequestsController(IRegister register)
        {
            _register = register;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FirstRequest()
        {
            RequestsVM requestsVM = new()
            {
                SelectUser = _register.User.GetAll()
                .Where(u => u.role == SD.Role_Employee || u.role == SD.Role_Admin)
                .Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.ID.ToString()
                })
            };
            return View(requestsVM);
        }
        [HttpPost]
		public IActionResult FirstRequest(RequestsVM requestsVM)
		{
			RequestsVM requestsVMUpdated = new RequestsVM();
			var purchaseList = _register.Purchase.GetAll();
			var selectListItems = new List<SelectListItem>();

			foreach (var purchase in purchaseList)
			{
				if (purchase.IDOfEmployee == requestsVM.User.ID)
				{
					var currency = _register.CurrencyInfo
						.GetFirstOrDefault(u => u.ID == purchase.CurrencyID);
					if (currency != null)
					{
						selectListItems.Add(new SelectListItem
						{
							Text = currency.Name,
							Value = currency.ID.ToString()
						});
					}
				}
			}
			requestsVMUpdated.SelectUser = _register.User.GetAll()
				.Where(u => u.role == SD.Role_Employee || u.role == SD.Role_Admin)
				.Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.ID.ToString()
				});
			requestsVMUpdated.User = requestsVM.User;
			requestsVMUpdated.SelectIAC = selectListItems;
			return View(requestsVMUpdated);
		}
		public IActionResult SecondRequest() 
		{
			List<User> ObjectsFromDb = new List<User>();
			ObjectsFromDb = _register.User.GetAll().Where(u => u.role == SD.Role_Employee).ToList();
			return View(ObjectsFromDb);
		}
        public IActionResult ThirdRequest()
        {
            return View();
        }
        [HttpPost]
		public IActionResult ThirdRequest(RequestsVM r) 
		{
			List<Purchase> ListOfPurchase = _register.Purchase.GetAll().Where(u=>u.DateOfMakingPurchase 
			>= r.StartDateTime && u.DateOfMakingPurchase <= r.EndDateTime).ToList();
            ViewBag.ListOfPurchase = ListOfPurchase;
            return View();
		}
		public IActionResult FourthRequest()
        {
            return View();
        }
        [HttpPost]
		public IActionResult FourthRequest(RequestsVM r) 
		{
			List<Purchase> ListOfPurchase = _register.Purchase.GetAll().Where(u=>u.DateOfMakingPurchase 
			>= r.StartDateTime && u.DateOfMakingPurchase <= r.EndDateTime).ToList();
            ViewBag.Count = ListOfPurchase.Count;
            return View();
		}
        public IActionResult FifthRequest()
        {
            int counter = 0;
            RequestsVM requestsVM= new RequestsVM();
            var purchaseList = _register.Purchase.GetAll();
            var currList = _register.CurrencyInfo.GetAll();
            var selectListItems = new List<SelectListItem>();
            foreach (var item in currList)
            {
                foreach (var purchase in purchaseList)
                {
                    if (item.ID == purchase.CurrencyID)
                    {
                        counter++;
                    }
                }
                selectListItems.Add(new SelectListItem
                {
                    Text = item.Name,
                    Value = counter.ToString()
                });
                counter = 0;

            }
            requestsVM.SelectIAC = selectListItems;
            return View(requestsVM);
        }
        public IActionResult SixthRequest() 
        {
            int counter = 0;
            RequestsVM requestVM = new RequestsVM();
            List<Purchase> pl = _register.Purchase.GetAll().ToList();
            List<User> ul = _register.User.GetAll().Where(u=>u.role==SD.Role_Customer).ToList();
            Dictionary<int, int> p = new Dictionary<int, int>();
            foreach (User u in ul) 
            {
                foreach(Purchase pur in pl) 
                { 
                    if(u.ID == pur.IDOfUser) 
                    {
                        counter++;
                    }
                }
                p.Add(u.ID, counter);
                counter = 0;
            }
            int IdOfUser = p.OrderByDescending(kvp => kvp.Value).First().Key;
            int Value = p.OrderByDescending(kvp => kvp.Value).First().Value;
            requestVM.User = _register.User.GetFirstOrDefault(u => u.ID == IdOfUser);
            ViewBag.Value = Value;
            return View(requestVM);
        }
        public IActionResult SeventhRequest() 
        {
            List<Payments> paymentsList = _register.Payments.GetAll().ToList();

            // Список типів платежів, які вас цікавлять
            List<string> typesOfInterest = new List<string>
            {
                SD.Payments_Type_Salary,
                SD.Payments_Type_BC,
                SD.Payments_Type_Util
            };


            DateTime oneMonthAgo = DateTime.Now.AddMonths(-1);
            List<string> paymentsLastMonth = paymentsList
                .Where(p => p.DateOfMakingPayments > oneMonthAgo && p.DateOfMakingPayments <= DateTime.Now)
                .Select(p => p.Type)
                .Distinct()
                .ToList();

            List<string> typesNotPerformedLastMonth = typesOfInterest
                .Where(t => !paymentsLastMonth.Contains(t))
                .ToList();

            ViewBag.ListWithTypes = typesNotPerformedLastMonth;
            return View();
        }
        public IActionResult EighthRequest() 
        {
            // Отримання всіх покупок
            List<Purchase> purchaseList = _register.Purchase.GetAll().ToList();

            // Отримання всіх користувачів з роллю клієнта
            List<User> userList = _register.User.GetAll()
                .Where(u => u.role == SD.Role_Customer).ToList();

            // Дата одного місяця тому
            DateTime oneMonthAgo = DateTime.Now.AddMonths(-1);

            // Відфільтрувати покупки за останній місяць
            List<Purchase> purchasesLastMonth = purchaseList
                .Where(p => p.DateOfMakingPurchase > oneMonthAgo && p.DateOfMakingPurchase <= DateTime.Now).ToList();

            // Отримати список ID користувачів, які зробили покупки за останній місяць
            List<int?> userIdsWithPurchasesLastMonth = purchasesLastMonth
                .Select(p => p.IDOfUser).Distinct().ToList();

            // Відфільтрувати користувачів, які не робили покупок за останній місяць
            List<User> usersWithoutPurchasesLastMonth = userList
                .Where(u => !userIdsWithPurchasesLastMonth.Contains(u.ID)).ToList();

            // Передати список користувачів у ViewBag для відображення
            ViewBag.UserList = usersWithoutPurchasesLastMonth;

            return View();
        }
        public IActionResult NinethRequest() 
        {
            // Отримання всіх покупок
            List<Purchase> purchaseList = _register.Purchase.GetAll().ToList();

            // Отримання всіх користувачів з роллю клієнта
            List<InfoAboutCurrency> currList = _register.CurrencyInfo.GetAll().ToList();

            // Дата одного місяця тому
            DateTime oneMonthAgo = DateTime.Now.AddMonths(-1);

            // Відфільтрувати покупки за останній місяць
            List<Purchase> purchasesLastMonth = purchaseList
                .Where(p => p.DateOfMakingPurchase > oneMonthAgo && p.DateOfMakingPurchase <= DateTime.Now).ToList();

            // Отримати список ID користувачів, які зробили покупки за останній місяць
            List<int?> currencyIdsWithPurchasesLastMonth = purchasesLastMonth
                .Select(p => p.CurrencyID).Distinct().ToList();

            // Відфільтрувати користувачів, які не робили покупок за останній місяць
            List<InfoAboutCurrency> currWithoutPurchasesLastMonth = currList
                .Where(u => !currencyIdsWithPurchasesLastMonth.Contains(u.ID)).ToList();

            // Передати список користувачів у ViewBag для відображення
            ViewBag.CurrList = currWithoutPurchasesLastMonth;

            return View();
        } 
        public IActionResult TenthRequest() 
        {
            List<Purchase> operationList = _register.Purchase.GetAll().ToList();

            List<User> employeeList = _register.User.GetAll()
                .Where(e => e.role == SD.Role_Employee).ToList();

            DateTime oneWeekAgo = DateTime.Now.AddDays(-7);

            List<Purchase> operationsLastWeek = operationList
                .Where(o => o.DateOfMakingPurchase > oneWeekAgo && o.DateOfMakingPurchase <= DateTime.Now)
                .ToList();

            List<int?> employeeIdsWithOperationsLastWeekNullable = operationsLastWeek
                .Select(o => o.IDOfEmployee)
                .Distinct()
                .ToList();

            List<int> employeeIdsWithOperationsLastWeek = employeeIdsWithOperationsLastWeekNullable
                .Where(id => id.HasValue)
                .Select(id => id.Value)
                .ToList();

            List<User> employeesWithOperationsLastWeek = employeeList
                .Where(e => employeeIdsWithOperationsLastWeek.Contains(e.ID))
                .ToList();

CourseProjectDB/Areas/Admin/Controllers/UserController.cs
using CP.DataAccess.Repository.IRepository;
using CP.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CourseProjectDB.Areas.Admin.Controllers
{
    [Authorize]
	[Authorize(Roles = "Admin")]
	[Area("Admin")]
	public class UserController : Controller
    {
        private readonly IRegister _register;
        public UserController(IRegister register)
        {
            _register = register;
        }
        public IActionResult Index()
        {
            List<User> ListOfObjects = _register.User.GetAll().ToList();
            return View(ListOfObjects);
        }

		#region API CALLS
		[HttpGet]
		public IActionResult GetAll()
		{
			List<User> ObjectsFromDb = _register.User.GetAll().ToList();
			return Json(new { data = ObjectsFromDb });
		}
		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			var UserToBeDeleted = _register.User.GetFirstOrDefault(u => u.ID == id);
			if (UserToBeDeleted == null)
			{
				return Json(new { succes = false, message = "Помилка під час видалення" });
			}
			List<Purchase> purchases = _register.Purchase.GetAll().ToList();
			foreach (Purchase purchase in purchases) 
			{
				if(purchase.IDOfUser == id) 
				{
					purchase.IDOfUser = null;
				}
			}
			_register.User.Delete(UserToBeDeleted);
			_register.Save();

			return Json(new { succes = true, message = "Користувача було видалено успішно!" });
		}
		#endregion
	}
}

CourseProjectDB/Views/Shared/_Layout.cshtml
@using CP.Utility.StatciData
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UkrainianExchangeGroup</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseProjectDB.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Обмін валют</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Purchase" asp-action="Index">Замовлення</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Currency" asp-action="Index">Список валюти</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Користувачі</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Payments" asp-action="Index">Платежі</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Requests" asp-action="Index">Запити</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link text-dark p-3" asp-area="Customer" asp-controller="Register" asp-action="Logout">Вихід</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark p-3" asp-area="Customer" asp-controller="Register" asp-action="Index">Реєстрація</a>
                        <a class="nav-link text-dark p-3" asp-area="Customer" asp-controller="Login" asp-action="Index">Вхід</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <p style="font-family: 'Vivaldi', monospace; font-size: 25px;" class="text-primary">Made by Pereverten</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/y6om4ux82785fymn1ce93psv4z2vk17x7nwsdve5rf8kdyc8/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="~/js/site.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CourseProjectDB/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">toastr.success('@TempData["success"]');</script>
}

@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js">@TempData["success"]</script>
	<script type="text/javascript">toastr.error('@TempData["success"]');</script>

}